name: Evaluate

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  upload-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run Go script to generate CSV
        run: go run *.go

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: exported-csv
          path: ./output.csv

